Update outdated email address (letters A and B)
datenanfragen/data pull request #1158
Opened 2021-06-23 21:19 UTC by baltpeter

As it turns out, our data is rotting a lot faster than I
expected.

This is the first batch of manual updates based on a tool
first proposed and implemented by @mal-tee that I have now
taken over.
So far, I have only completed the results for companies with
slugs starting with A and B, and the tool currently only checks
the email addresses.

Clearly, this is an important problem that we will need to deal
with. The ultimate goal for the tool is to automatically run it
periodically and report its findings as issues on this repo. This
is however not implemented yet but I will prioritize working on it.
I will also manually handle the first batch of findings mysel as
we would otherwise be completely overwhelmed with issues.
Hopefully, this will become more manageable once we actually
start regularly checking everything.

2021-06-23 21:21 UTC, baltpeter commented
@mal-tee Obviously, it will take me a while to go through the remaining problems. Nonetheless, I think it makes sense to start merging my changes incrementally.

Feel free to decide yourself how thoroughly you want to review the changes. I am mostly submitting them as PR to illustrate how severe the problem actually is (I am honestly quite shocked myself).

2021-06-27 13:23 UTC, mal-tee requested changes
Wow, really that's a lot! Thank you!

I've limited my "review" to running my (slightly extended) semgrep-rule for s-t-m and found one case. There a plenty of other in the whole of `data`, but I think I will wait for you to finish keep-aliving the rest before I fix them.

2021-06-27 13:23 UTC, mal-tee commented on companies/arvato-infoscore.json
> +    "email": "datenschutz-aig@arvato.com",
Please set suggested-transport-medium as well :D

2021-06-28 10:01 UTC, baltpeter commented
Please squash when merging.

2021-06-28 12:35 UTC, mal-tee approved these changes
Thanks!

2021-06-28 12:35 UTC, merged