Add 'Höffner Online GmbH & Co. KG' (community contribution)
datenanfragen/data pull request #1297
Opened 2021-09-17 18:20 UTC by datenanfragen-community-edits

This suggestion was submitted through the website.

2021-10-01 22:14 UTC, moriarty-jim requested changes
some fixes/suggestions

2021-10-01 22:14 UTC, moriarty-jim commented on companies/hoeffner.json
> +    "phone": "+49 (0)30 37444 -02  und +49 (0)39205 61-333 ",
```suggestion
    "phone": "+49 30 3744402",
```
I would suggest to use only the first number, the second one is for "online customer service"

2021-10-01 22:14 UTC, moriarty-jim commented on companies/hoeffner.json
> +    "address": "Am Rondell 1\n12529 Schönefeld",
```suggestion
    "address": "Am Rondell 1\n12529 Schönefeld\nDeutschland",
```
fixed address

2021-10-01 22:14 UTC, moriarty-jim commented on companies/hoeffner.json
> +    "email": " onlineservice@hoeffner.de",
```suggestion
    "email": "datenschutz@hoeffner.de",
```
specific email-address for DPO

2021-10-02 08:08 UTC, mal-tee approved these changes
Thanks to both of you!

2021-10-02 08:08 UTC, merged