Add 'Internet TV AG' (community contribution)
datenanfragen/data pull request #1350
Opened 2021-09-29 15:15 UTC by datenanfragen-community-edits

This suggestion was submitted through the website.

2021-09-29 15:19 UTC, WebworkrNet commented
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

2021-10-01 21:56 UTC, moriarty-jim requested changes
fixed address and suggestion for `relevant-countries` (optional)

2021-10-01 21:56 UTC, moriarty-jim commented on companies/onlinetvrecorder.json
> +    "address": "306 Victoria House\n361 Victoria\nSeychelles\n\n",
```suggestion
    "address": "306 Victoria House\nVictoria Mahe\nSeychelles",
```
fixed formatting; see [https://www.onlinetvrecorder.com/v2/contact/gdpr](https://www.onlinetvrecorder.com/v2/contact/gdpr)

2021-10-01 21:56 UTC, moriarty-jim commented on companies/onlinetvrecorder.json
> +        "de"
```suggestion
        "all"
```
I would suggest "all" as the service is available worldwide and in multiple languages.

2021-10-02 09:00 UTC, baltpeter reviewed
Thanks, everyone!

2021-10-02 09:01 UTC, baltpeter approved these changes

2021-10-02 09:01 UTC, merged