Add remaining ProSiebenSat.1 brands
datenanfragen/data pull request #1393
Opened 2021-10-07 13:59 UTC by vikramadityasinghs

Issue #1255 
Added json files for the remaining 8 websites, brands and apps run by Sat.1 in /companies.

2021-11-02 06:19 UTC, vikramadityasinghs reviewed
hi @mal-tee, I have made all the required changes.
if there wasn't a verified source of a fax number I omited it from the json file.

2021-11-02 06:26 UTC, vikramadityasinghs reviewed
updated sixx.json

2021-11-05 15:22 UTC, mal-tee commented on companies/kabeleins.json
> +    "fax": "+49 89 3977199",
Sorry for taking so long -- yes, if there is no source we should omit it.

2021-11-05 15:44 UTC, mal-tee requested changes
Thank you! I've left some comments.

2021-11-05 15:44 UTC, mal-tee commented on companies/joyn-gmbh.json
> +    "address": "Ridlerstrasse 57\n80339 Munich\nGermany",
```suggestion
    "address": "Ridlerstrasse 57\n80339 München\nGermany",
```

2021-11-05 15:44 UTC, mal-tee commented on companies/joyn-gmbh.json
> +    "fax": "+49 89 3977199",
```suggestion
    "fax": "+49 89 943977199,
```
that's the number from the "impressum"

2021-11-05 15:44 UTC, mal-tee commented on companies/kabeleins.json
> +        "https://www.sevenonemedia.de/impressum"
```suggestion
```

2021-11-05 15:44 UTC, mal-tee commented on companies/kabeleinsdoku.json
> +    "name": "Seven.One Entertainment Group GmbH",
please add a `runs`  with "Kabel Eins Doku", to improve the value of this record

2021-11-05 15:44 UTC, mal-tee commented on companies/prosieben.json
> +        "https://www.sevenonemedia.de/impressum",
```suggestion
```

2021-11-05 15:44 UTC, mal-tee commented on companies/prosiebenmaxx.json
> +    "address": "Medienallee 4\nD-85774 Unterföhring\nGermany",
```suggestion
    "address": "Medienallee 4\n85774 Unterföhring\nGermany",
```

2021-11-05 15:44 UTC, mal-tee commented on companies/prosiebenmaxx.json
> +        "https://www.prosiebenmaxx.de/service/impressum"
```suggestion
```

2021-11-05 15:44 UTC, mal-tee commented on companies/ran.json
> +    "address": "Medienallee 7\n85774 Unterföhring\nGermany",
```suggestion
    "address": "c/o ProSiebenSat.1 Media SE\nMedienallee 7\n85774 Unterföhring\nGermany",
```

2021-11-05 15:44 UTC, mal-tee commented on companies/sat1gold.json
> +    "address": "Medienallee 7\nD-85774 Unterföhring\nGermany",
```suggestion
    "address": "Medienallee 7\n85774 Unterföhring\nGermany",
```

2021-11-05 15:44 UTC, mal-tee commented on companies/sat1gold.json
> +        "https://www.sat1gold.de/service/impressum"
```suggestion
```

2021-11-05 15:44 UTC, mal-tee commented on companies/sixx.json
> +    "phone": "+49 89 95072898",
```suggestion
    "phone": "+49 89 950710",
```

2021-11-05 15:45 UTC, mal-tee commented
I took the liberty and merged master, which includes better tests :)

2021-11-07 10:45 UTC, vikramadityasinghs reviewed
I've made the particular changes you requested, sorry I will keep it in mind 👍 @mal-tee

2021-11-07 11:08 UTC, vikramadityasinghs reviewed
Fixing some minute errors

2021-11-07 11:23 UTC, vikramadityasinghs reviewed
fixed the errors

2021-11-09 09:47 UTC, mal-tee requested changes

2021-11-09 09:47 UTC, mal-tee commented on companies/kabeleinsdoku.json
> +        "www.kabeleinsdoku.ch"
```suggestion
        "Kabel Eins Doku"
```

2021-11-09 09:48 UTC, mal-tee approved these changes
Thank you! I'll wait for the tests and merge.

2021-11-09 09:51 UTC, merged

2021-11-09 16:30 UTC, vikramadityasinghs commented
thanks a lot! @mal-tee hope to work  on this repo again :smile: