Change "dataxu" to "Roku"
datenanfragen/data pull request #1514
Opened 2021-10-28 20:35 UTC by GonzoJurezz

Issue #1511

2021-10-31 19:00 UTC, baltpeter requested changes
Thanks for the record! I have requested some changes below.

2021-10-31 19:00 UTC, baltpeter commented on companies/roku.json
> +    "web": "https://www.roku.com/de-de/",
```suggestion
    "web": "https://www.roku.com/",
```

2021-11-01 20:53 UTC, GonzoJurezz commented on companies/roku.json
> +    ],
I used their contact form as a source for the required elements. They have mentioned them in their contact form, so I thought, they need the same required elements with email.

2021-11-01 20:54 UTC, GonzoJurezz commented on companies/roku.json
> +        "https://privacy.roku.com/contact/anonymous"
https://github.com/datenanfragen/data/pull/1514#discussion_r739862632

2021-11-01 20:56 UTC, GonzoJurezz commented on companies/roku.json
> +        "https://privacy.roku.com/contact/anonymous"
I wanted to hightligt, that there is another option for users with a roku account. Or should I mention it in the comments?

2021-11-07 15:31 UTC, baltpeter approved these changes
Thank you!

2021-11-07 15:32 UTC, merged