Add BITel, T.W.O. and Stadtwerke Bielefeld
datenanfragen/data pull request #740
Opened 2020-10-03 16:51 UTC by KoesterD

T.W.O. and Stadtwerke Bielefeld are utility companies. BITel is a telco.

I'm unsure about the super short slug for T.W.O. ("two"), but it's not yet used. Alternatively "two-de" or "technische-werke-osning" could be used.

2020-10-04 08:52 UTC, baltpeter requested changes
Thanks for the records! Just two small comments below.

2020-10-04 08:52 UTC, baltpeter commented on companies/two.json
> +    "slug": "two",
I agree that `two` is a little too generic. Let's use `technische-werke-osning` instead.

2020-10-04 08:52 UTC, baltpeter commented on companies/two.json
> +    "address": "Hopfengarten 10\n33775 Versmold\nDeutschland",
As this is the address of the external DPO, we need to mention that company's name to make sure letters actually arrive.

```suggestion
    "address": "c/o EDV-Unternehmensberatung Floß GmbH\nHopfengarten 10\n33775 Versmold\nDeutschland",
```

2020-10-10 13:52 UTC, KoesterD commented
Thanks for the review!
I changed the slug and address of Technische Werke Osning as requested.

2020-10-10 13:56 UTC, baltpeter approved these changes
Thanks again!

2020-10-10 13:56 UTC, merged