Add Landespolizei des Fürstentums Liechtenstein
datenanfragen/data pull request #757
Opened 2020-10-05 21:16 UTC by Double-A-92

2020-10-06 09:01 UTC, baltpeter requested changes
Thanks for the record. I think specifying `Datenschutz@regierung.li` as the email is better. What do you think?

2020-10-06 09:01 UTC, baltpeter commented on companies/landespolizei-des-fuerstentums-liechtenstein.json
> +    "email": "info@landespolizei.li",
Considering the Regierungskanzlei is mentioned as the data protection officer in the privacy policy, I think we should use the `Datenschutz@regierung.li` email.

2020-10-23 09:56 UTC, mal-tee commented
To chime in: 

This address is related to several other institutions, see https://www.llv.li/inhalt/918657/amtsstellen/fachstelle-datenschutz

2021-01-21 20:06 UTC, baltpeter approved these changes
Thank you!

2021-01-21 20:07 UTC, merged