WIP: Add e-scooter
datenanfragen/data pull request #822
Opened 2020-11-05 09:39 UTC by mal-tee

2020-11-06 16:04 UTC, baltpeter requested changes
Thank you!

2020-11-06 16:04 UTC, baltpeter commented on bird-rides-europe.json
> +    "email": "hello@bird.co",
Please add the website.

2020-11-06 16:04 UTC, baltpeter commented on tier-mobility.json
> +    "web": "www.tier.app",
```suggestion
    "web": "https://www.tier.app",
```

2020-11-07 10:33 UTC, mal-tee commented on bird-rides-europe.json
> +    "email": "hello@bird.co",
Oops, done.

2020-11-07 10:35 UTC, baltpeter approved these changes

2020-11-07 10:36 UTC, merged